server {

    listen 80;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        log_not_found off;
        access_log off;
    }

    # Optional: Gzip compression for faster delivery.
    # Gzip compresses files before sending them to the client, reducing bandwidth usage.
    gzip on;
    # Specify which MIME types should be zipped
    gzip_types text/plain text/css application/javascript application/json text/xml application/xml application/xml+rss text/javascript;
    # Allow zipping for proxied requests
    gzip_proxied any;
    # Add a 'Vary: Accept-Encoding' header, informing proxies that the response varies based on the client's Accept-Encoding header
    gzip_vary on;
    # Set the compression level (1-9, 6 is a good balance)
    gzip_comp_level 6;
    # Set number & size of buffers used for compression
    gzip_buffers 16 8k;
    # Specify minimum HTTP version of the request for which to enable Gzip
    gzip_http_version 1.1;
}